homepage/urls.py
from django.urls import path


from . import views


urlpatterns = [
    path('', views.index, name='homepage'),
]

ms/urls.py
from django.contrib import admin
from django.urls import path, include
from . import view


urlpatterns = [
    path('', view.index),
    path('admin/', admin.site.urls),
    path('querycode/', include('querycode.urls')),
]

querycode/urls.py
from django.urls import path


from . import views

app_name = 'qc'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
]

homepage/models.py
from django.db import models

# Create your models here.

querycode/models.py
from django.db import models


class AuCode(models.Model):
    code = models.CharField(max_length=30)
    add_date = models.DateTimeField('date added')

    def __str__(self):
        return self.code

homepage/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'homepage.html')

querycode/views.py
from django.shortcuts import render, get_object_or_404


from .models import AuCode


def index(request):

    return render(request, 'querycode/index.html')


def detail(request):
    # ac = get_object_or_404(AuCode, code=request.GET.get('name'))
    ac = request.GET.get('name')
    error_msg = ''
    if not ac:
        error_msg = "You didn't input anything, try again!"
        return render(request, 'querycode/detail.html', {
            'error_msg': error_msg,
        })
    aucode = AuCode.objects.filter(code=ac)

    if not aucode:
        error_msg = "Don't match any report,please note the case"
        return render(request, 'querycode/detail.html', {
            'error_msg': error_msg,

        })


    return render(request, 'querycode/detail.html', {
        'aucode': aucode,


    })

querycode/templates/querycode/index.html
{% extends 'base.html' %}
{% block page-css%}
<!-- Custom styles for this template -->
{% load static%}
<link href="{% static 'bootstrap/css/carousel.css' %}" rel="stylesheet">
{% endblock %}
{% block content%}
<div class="container">
    <div class="intro">
        <div class="row">
          <div class="col text-center">
            <span class="preheader">ANALYSIS &amp; GRADING</span>
            <h1>Report Check</h1>
            <p class="lead"></p><p>
	<span class="suppress-on-mobile">GIA reports represent the highest standard of reliability, consistency and integrity. And now, GIA Report Check is available for all GIA reports, providing you with an additional level of assurance.</span> With Report Check, you can quickly and conveniently confirm that the information on your report matches what is archived in the GIA report database.</p>
<p></p>
          </div>
        </div>
      </div>
<section class="report-check-landing">
        <section class="report-check">
          <form action="{% url 'qc:detail'%}" method="get" class="report-lookup-form" role="form">
              {% csrf_token %}
              <div class="form-inline">
                  <div class="form-group">

                      <label for="name">Look Up A Report</label>
                      <input type="text" class="form-control" id="name" placeholder="Enter Report Number" required>
                  </div>
              <button type="submit" class="btn btn-default">submit</button>
              </div>

          </form>

          <h3>report check features</h3>
            <table class="table">
                <tbody><tr></tr>
                <tr>
                    <td><strong>For reports dated on or after:</strong></td>
                    <td><strong>January 1, 2000</strong></td>
                    <td><strong>July 1, 2010</strong></td>
                    <td><strong>January 1, 2014</strong></td>
                    <td><strong>February 1, 2015</strong>
                    </td></tr><tr><td>Report data</td>
                    {% load static %}
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                    <td style="text-align: center;"><span style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></span></td>
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                </tr>
                <tr>
                    <td>PDF facsimile of report</td>
                    <td>&nbsp;</td>
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                </tr>
                <tr>
                    <td>
                        Image of item, plotted diagram, and/or<br>proportion diagram (where applicable)</td>
                    <td>&nbsp;</td><td style="text-align: center;">&nbsp;</td>
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                </tr>
                <tr>
                    <td>Treatment Description Tab (where applicable)</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td style="text-align: center;"><img src="{% static '/images/icon-green-check.png'%}"></td>
                </tr>
                </tbody>
            </table>
                <p class="suppress-on-mobile">Need an easy way to regularly check multiple reports? You may qualify for Report Check Plus.<a href="http://www.gia.edu/gem-lab-report-check-plus"> Learn More</a></p></center><br>

          <h3>important limitations</h3>

          <p>GIA does not make any representations or warranties regarding the information returned by Report Check, which may not display all the information included on the original Report issued by GIA. All Report Check information is subject to these<a href="https://www.gia.edu/terms" class="">limitations.</a></p>
        </section>
      </section>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Gemological Detection Of America | ALL About Gemstones -GDA</title>
      <!-- Bootstrap core CSS -->
    {% load static%}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'bootstrap/css/ie10-viewport-bug-workaround.css' %}">



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
      {% block page-css%}
      {% endblock %}


  </head>
<!-- NAVBAR
================================================== -->
  <body>

    {% load static%}
    {% include 'navbar.html'%}
    {% include 'carousel.html'%}

    {%block content%}
    {% endblock %}

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->


    <div class="container">
      <div class="row">
              <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2019 GDA, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'bootstrap/js/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'bootstrap/js/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

templates/carousel.html
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          {% load static %}
          <img class="first-slide" src="{% static 'images/jewels-of-hollywood-1280x550.jpg'%}" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>FEATURE ARTICLE.</h1>
              <p>Jewels of Hollywood: Accessories and Jewelry that Made the Starts Shine</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">READ MORE</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static 'images/Black-Nephrite-Jade-1280x550.jpg'%}" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>GEMS & GEMOLOGY</h1>
              <p>Black Nephrite Jade from Guangxi, Southern china.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="{% static 'images/Rotation-Flame-Structure-Pearls.jpg'%}" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>GEMS & GEMOLOGY</h1>
              <p>Evidence of Rotation in Flame-Structure Peaarls.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">READ MORE</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

templates/homepage.html
{% extends 'base.html' %}


{% block page-css%}
<!-- Custom styles for this template -->
{% load static%}
<link href="{% static 'bootstrap/css/carousel.css' %}" rel="stylesheet">
{% endblock %}


{% block content%}
   <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'images/diamond.png'%}" alt="Generic placeholder image" width="140" height="140">
          <h2>DIAMOND</h2>
          <p>Diamonds are among nature’s most precious and beautiful creations.</p>

        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'images/fancy-color-diamond.png'%}" alt="Generic placeholder image" width="140" height="140">
          <h2>FANCY COLOR DIAMOND</h2>
          <p>Dazzling brilliance. Captivating color. These are the planet’s most valued gems.</p>

        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'images/Featured-Gems-CITRINE-151544-73x70.png'%}" alt="Generic placeholder image" width="140" height="140">
          <h2>CITRINE</h2>
          <p>Citrine is the transparent, pale yellow to brownish orange variety of quartz.</p>

        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">LABORATORY-GROWN DIAMOND GRADING REPORT</h2>
          <p class="lead">Full 4Cs assessment with general color and clarity descriptions. For loose, colorless to near-colorless laboratory-grown diamonds, 0.15 carats or more.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="{% static 'images/resources-for-retailers.jpg' %}" alt="LABORATORY-GROWN DIAMOND">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->


    </div><!-- /.container -->
{% endblock%}

templates/navbar.html
 <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              {% load static%}
              <a class="navbar-brand" href="#"><img src="{% static 'images/gdalogo.svg'%}" alt="logo" height="40"  > </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">HOME</a></li>
                <li><a href="#about">About US </a></li>
                <li><a href="#contact">Contact US</a></li>
                  <li><a href="/querycode">REPORT CHECK</a></li>
                <!--<li class="dropdown">-->
                  <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
                  <!--<ul class="dropdown-menu">-->
                    <!--<li><a href="#">Action</a></li>-->
                    <!--<li><a href="#">Another action</a></li>-->
                    <!--<li><a href="#">Something else here</a></li>-->
                    <!--<li role="separator" class="divider"></li>-->
                    <!--<li class="dropdown-header">Nav header</li>-->
                    <!--<li><a href="#">Separated link</a></li>-->
                    <!--<li><a href="#">One more separated link</a></li>-->
                  <!--</ul>-->
                <!--</li>-->
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>